name: Trigger tag update for staging environment

on:
  workflow_dispatch:

jobs:
  get-image-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Image Tags
        id: get-image-tags
        run: |
          echo "github.workspace: ${{ github.workspace }}"
          TAGS=$(bash ${{ github.workspace }}/scripts/get-image-tags.sh 2>/dev/null)
          echo "image_tags_json=$TAGS" >> $GITHUB_OUTPUT
    outputs:
      image_tags_json: ${{ steps.get-image-tags.outputs.image_tags_json }}

  trigger-tag-update:
    needs: get-image-tags
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT_ORGANIZATION }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'BeaverHouse',
              repo: 'github-action-exp-target',
              workflow_id: 'helm-tag-updates.yaml',
              ref: 'main',
              inputs: {
                images: "${{ needs.get-image-tags.outputs.image_tags_json }}",
                values_files: "charts/tag-update/values-stg.yaml",
                target_branch: "main",
                source_commit: "${{ github.sha }}",
                source_repository: "${{ github.repository }}",
                auto_merge: "true"
              }
            })
